### ISSUE TITLE
Error: Something went wrong during encryption

### ISSUE THREAD

**Issue by serbinskis** [joshuaquek/QuickEncrypt#23]
QuickEncrypt.encrypt("1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111", QuickEncrypt.generate(1024).public);

Error: Something went wrong during encryption
    at UnknownError (D:\Temporary\Dekstop\test123\node_modules\quick-encrypt\index.js:4:35)
    at Object.exports.encrypt (D:\Temporary\Dekstop\test123\node_modules\quick-encrypt\index.js:18:11)

**Comment by serbinskis** [comment]
nvm, it is RSA limits
